#!/usr/bin/make -f

default: all

all:
	aclocal
	autoheader
	automake
	autoconf

DIST_FILE=dmtcp-0.12.tar.bz2

dist:
	make -f Makefile distclean || true
	rm -f dmtcp.kdevelop.pcs ../$(DIST_FILE)
	rm -rf autom4te.cache
	(find | grep ~$$ | xargs rm) || true
	(find | grep ckpt_ | grep mtcp$$ | xargs rm) || true
	(cd .. && tar jcvf $(DIST_FILE) `basename $(PWD)`)
	ls -lh ../$(DIST_FILE)
