Document: dmtcp
Title: Debian dmtcp Manual
Author: <insert document author here>
Abstract: This manual describes what dmtcp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dmtcp/dmtcp.sgml.gz

Format: postscript
Files: /usr/share/doc/dmtcp/dmtcp.ps.gz

Format: text
Files: /usr/share/doc/dmtcp/dmtcp.text.gz

Format: HTML
Index: /usr/share/doc/dmtcp/html/index.html
Files: /usr/share/doc/dmtcp/html/*.html

  
