#!/bin/bash
# Put your SLURM options here
#SBATCH --partition=debug         # change to proper partition name or remove
#SBATCH --time=00:15:00           # put proper time of reservation here
#SBATCH --nodes=2                 # number of nodes
#SBATCH --ntasks-per-node=4       # processes per node
#SBATCH --mem=24000               # memory resource
#SBATCH --job-name="dmtcp_job"    # change to your job name
#SBATCH --output=0_rstr.out        # change to proper file name or remove for defaults
#SBATCH --error=0_rstr.err        # change to proper file name or remove for defaults
# ? Any other batch options ?

# Start dmtcp coordinator on launching node. Free TCP port is automatically allocated.
# this function creates dmtcp_command.$JOBID script that serves like a wrapper around
# dmtcp_command that tunes it on exact dmtcp_coordinator (it's hostname and port)
# instead of typing "dmtcp_command -h <coordinator hostname> -p <coordinator port> <command>"
# you just type "dmtcp_command.$JOBID <command>" and talk to coordinator of JOBID job
start_coordinator()
{
#    export DMTCP_COORD_HOST=f07n05
#    export DMTCP_COORD_PORT=7779
#    return


    fname=dmtcp_command.$SLURM_JOBID
    h=`hostname`
    dmtcp_coordinator --daemon --exit-on-last -p 0 --port-file $fname $@ 1>/dev/null 2>&1
    
    while true; do 
        if [ -f "$fname" ]; then
            p=`cat $fname`
            if [ -n "$p" ]; then
                # try to communicate ? dmtcp_command -p $p l
                break
            fi
        fi
    done
    
    # Create dmtcp_command wrapper for easy communication with coordinator
    p=`cat $fname`
    chmod +x $fname
    echo "#!/bin/bash" > $fname
    echo >> $fname
    echo "export PATH=$PATH" >> $fname
    echo "export DMTCP_COORD_HOST=$h" >> $fname
    echo "export DMTCP_COORD_PORT=$p" >> $fname
    echo "dmtcp_command \$@" >> $fname

    # Setup local environment for DMTCP
    export DMTCP_COORD_HOST=$h
    export DMTCP_COORD_PORT=$p

}


# Print out SLURM job information. Remove it if you don't need it
echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR
echo "working directory = "$SLURM_SUBMIT_DIR

# changedir to workdir
cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR

# Some initial setup like 
# 1. Loading MPI or any other modules if you use modules.
#module load  openmpi/gcc-4.4.6/1.6
module load openmpi/gcc-4.4.6/1.6.5

module list
# 2. Make sure that DMTCP install prefix is in PATH & LD_LIBRARY_PATH. Remove if you sure about that.
export PATH="/ifs/user/artempol/sandbox/bin/":$PATH
export LD_LIBRARY_PATH="/ifs/user/artempol/sandbox/lib/":$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="$SLURM_SUBMIT_DIR/lib/":$LD_LIBRARY_PATH

#export PATH="/user/artempol/openmpi-build/bin/":$PATH
#export LD_LIBRARY_PATH="/user/artempol/openmpi-build/lib/":$LD_LIBRARY_PATH
# 3. Other settings
ulimit -s unlimited

export PMI_DEBUG=40

start_coordinator # -i 120 ... <put dmtcp coordinator options here>

echo "Start"
date 


rm -Rf LOGS/*

/bin/bash dmtcp_restart_script.sh -h $DMTCP_COORD_HOST  -p $DMTCP_COORD_PORT

echo "Finish"
date 
