#!/bin/bash
# Put your SLURM options here
#SBATCH --time=00:15:00           # put proper time of reservation here
#SBATCH --nodes=2                 # number of nodes
#SBATCH --ntasks-per-node=2       # processes per node
#SBATCH --job-name="hellompi_c"
#SBATCH --output=hellompi_c.std
#SBATCH --error=hellompi_c.err
# ? Any other batch options ?

# Start dmtcp coordinator on launching node. Free TCP port is automatically allocated.
# this function creates dmtcp_command.$JOBID script that serves like a wrapper around
# dmtcp_command that tunes it on exact dmtcp_coordinator (it's hostname and port)
# instead of typing "dmtcp_command -h <coordinator hostname> -p <coordinator port> <command>"
# you just type "dmtcp_command.$JOBID <command>" and talk to coordinator of JOBID job
start_coordinator()
{
    fname=dmtcp_command.$SLURM_JOBID
    h=`hostname`

    check_coordinator=`which dmtcp_coordinator`
    if [ -z "$check_coordinator" ]; then
        echo "No dmtcp_coordinator found. Check your DMTCP installation and PATH settings"
        exit 0
    fi

    dmtcp_coordinator --daemon --exit-on-last -p 0 --port-file $fname $@ 1>/dev/null 2>&1
    
    while true; do 
        if [ -f "$fname" ]; then
            p=`cat $fname`
            if [ -n "$p" ]; then
                # try to communicate ? dmtcp_command -p $p l
                break
            fi
        fi
    done
    
    # Create dmtcp_command wrapper for easy communication with coordinator
    p=`cat $fname`
    chmod +x $fname
    echo "#!/bin/bash" > $fname
    echo >> $fname
    echo "export PATH=$PATH" >> $fname
    echo "export DMTCP_HOST=$h" >> $fname
    echo "export DMTCP_PORT=$p" >> $fname
    echo "dmtcp_command \$@" >> $fname

    # Setup local environment for DMTCP
    export DMTCP_HOST=$h
    export DMTCP_PORT=$p

}


# Print out SLURM job information. Remove it if you don't need it
echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR
echo "working directory = "$SLURM_SUBMIT_DIR

# changedir to workdir
cd $SLURM_SUBMIT_DIR

# Some initial setup like 
. patch_env.sh

start_coordinator # -i 120 ... <put dmtcp coordinator options here>

echo "Start"
date

dmtcp_launch --rm --ib mpirun --mca btl tcp,self ./md_pc_mpi

echo "Finish"
date

srun ./slurm_collect.sh
